services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py createadmin && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - ADMIN_USERNAME=journaladmin
      - ADMIN_EMAIL=admin@journal.com
      - ADMIN_PASSWORD=adminpassword
    networks:
      - proxynet
    restart: "on-failure"

  db:
    image: postgres:12-bullseye
    networks:
      - proxynet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=journal
      - POSTGRES_PASSWORD=journal
      - POSTGRES_DB=journal
    restart: "on-failure"

networks:
  proxynet:
    name: journal_project

volumes:
  postgres_data: